---
title: ""
execute:
  echo: false
---

```{r}

library(tidyverse)
library(lubridate)

data <- readRDS("clean_airline_data.rds")



premium_airlines <- c(
  "Lufthansa",
  "Emirates",
  "Air France",
  "British Airways"
)


premium_data <- data %>%
  filter(AirlineName %in% premium_airlines)

Premium_Factors <- premium_data %>%
  summarise(
    PriceValue = mean(PriceValue, na.rm = TRUE),
    Comfort = mean(Comfort, na.rm = TRUE),
    ServiceQuality = mean(ServiceQuality, na.rm = TRUE),
    OnboardProduct = mean(OnboardProduct, na.rm = TRUE)
  ) %>%
  pivot_longer(
    everything(),
    names_to = "Factor",
    values_to = "AverageRating"
  )

ggplot(
  Premium_Factors,
  aes(
    x = reorder(Factor, AverageRating),
    y = AverageRating,
    fill = Factor
  )
) +
  geom_col(width = 0.6, show.legend = FALSE) +
  coord_flip() +
  scale_fill_brewer(palette = "Set3") +
  labs(
    title = "What drives airline choice for full-service carriers?",
    subtitle = "Lufthansa, Emirates, Air France, British Airways",
    x = "",
    y = "Average passenger rating"
  ) +
  theme_minimal(base_size = 15)




```

```{r}
Premium_Time <- premium_data %>%
  group_by(Year) %>%
  summarise(
    PriceValue = mean(PriceValue, na.rm = TRUE),
    Comfort = mean(Comfort, na.rm = TRUE),
    ServiceQuality = mean(ServiceQuality, na.rm = TRUE),
    OnboardProduct = mean(OnboardProduct, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_longer(
    -Year,
    names_to = "Factor",
    values_to = "AverageRating"
  )

ggplot(
  Premium_Time,
  aes(
    x = Year,
    y = AverageRating,
    color = Factor
  )
) +
  geom_line(linewidth = 1.2) +
  scale_color_brewer(palette = "Set1") +
  labs(
    title = "Evolution of passenger priorities for full-service airlines",
    subtitle = "1995–2024",
    x = "",
    y = "Average rating"
  ) +
  theme_minimal(base_size = 15)
```
